version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: node
    volumes:
    - ./:/usr/src/app
    command: sh -c "cd go-movies && yarn start"
    ports:
    - "3000:3000"
    stdin_open: true